- name: install Jupyter packages
  pip:
    executable: pip3
    name: jupyter

- name: install additional jupyter kernels
  pip:
    executable: pip3
    name: "{{ item }}"
    state: latest
  with_items:
    - bash_kernel

- name: enable extra jupyter kernels
  shell: "/usr/bin/python3 -m {{ item }} install"
  with_items:
    - bash_kernel

- name: create the Jupyter user
  user:
    name: jupyter
    comment: "jupyter user"
    shell: /bin/bash

- name: set up the configuration file
  file:
    path: "~{{ jupyter_user}}/.jupyter"
    state: directory
    owner: "{{ jupyter_user}}"
    group: "{{ jupyter_user }}"
    mode: 0755

- template:
    src: roles/jupyter/templates/jupyter_notebook_config.py.j2
    dest: "~{{ jupyter_user }}/.jupyter/jupyter_notebook_config.py"
    owner: "{{ jupyter_user}}"
    group: "{{ jupyter_user }}"
    mode: 0644

- name: create jupyter user notebook directory
  file:
    path: "~{{ jupyter_user}}/notebooks"
    state: directory
    owner: "{{ jupyter_user}}"
    group: "{{ jupyter_user }}"
    mode: 0755

- name: create systemd service script
  template:
    src: roles/jupyter/templates/jupyter.service.j2
    dest: /lib/systemd/system/jupyter.service
    mode: 0644

- name: enable jupyter via systemd
  systemd:
    name: jupyter
    enabled: yes
    state: started
