- name: install brew packages
  homebrew:
    name: "{{ item }}"
    state: latest
  with_items: "{{ brew_packages }}"

- name: install brew casks
  homebrew_cask:
    name: "{{ item }}"
    state: latest
  with_items: "{{ brew_casks }}"
